[project]
name = "tic-tac-toe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "graphviz>=0.20.3",
    "pytest>=8.3.4",
]
[tool.pytest.ini_options]
pythonpath = [
    ".", "src"
]
